version: '3.6'
services:
  prisma-postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
